name: Update API Dockerhub Images

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@master

      - uses: docker/setup-buildx-action@v1
        with:
          use: linux/amd64,linux/arm64,linux/arm64/v8

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Dockerhub Release
        run: ./scripts/release-dockerhub.sh -s api
